name: group-migration
run-name: migrate GitLab group porjects to GitHub organization
on:
  workflow_dispatch:
    inputs:
      github_user_name:
        description: "GitHub user name"
        required: true
        type: string
      gitlab_group_name:
        description: "GitLab group name"
        required: true
        type: string

jobs:
    get-all-projects:
        runs-on: ubuntu-latest
        outputs:
            ALL_PROJECTS: ${{ steps.parsed-projects-ids.outputs.PROJECTS_IDs }}
        steps:
            - name: Check out the repository on the runner
              uses: actions/checkout@v4
              with:
                persist-credentials: false

            - name: Get all projects in GitLab group
              env:
                GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
                PARSER_PY_FILE_PATH: ./parser_scripts/gitlab_group_project_info_parser.py
                PARSED_OUTPUT_FILE_PATH: ./api_calls_info/all_gitlab_group_projects.json
              run: |
                all_projects=$(curl --header "Authorization: Bearer ${{ env.GITLAB_TOKEN }}" "https://gitlab.com/api/v4/groups/test-migration-group/projects?simple=true")
                echo "${all_projects}" > ${{ env.PARSED_OUTPUT_FILE_PATH }}
                chmod +x ${{ env.PARSER_PY_FILE_PATH }}
                python ${{ env.PARSER_PY_FILE_PATH }}

            - name: Parse Json format of project data and store in GITHUB_OUTPUT
              id: parsed-projects-ids
              env:
                GH_TOKEN: ${{ secrets.GH_TOKEN }}
                FILE_PATH: ./parser_outputs/parsed.json
              run: |
                chmod +x ${{ env.FILE_PATH }}
                projects_ids=$(jq -c '.projects' ${{ env.FILE_PATH }})
                echo "PROJECTS_IDs=${projects_ids}" >> "$GITHUB_OUTPUT"

    migrate-group:
        needs: get-all-projects
        strategy:
            matrix:
                repositories: ${{ fromJSON(needs.get-all-projects.outputs.ALL_PROJECTS) }}
            max-parallel: 1
        uses: ./.github/workflows/migration_template.yml
        with:
            migration_type: "repo"
            script_file_path: "./repo-migration.sh"
            is_github_organisation: true
            github_user_name: ${{ inputs.github_user_name }}
            github_repo_name: ${{ matrix.repositories }}
            gitlab_user_name: ${{ inputs.gitlab_group_name }}
            gitlab_repo_name: ${{ format('https://gitlab.com/test-migration-group/{0}', matrix.repositories) }}
        secrets: 
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
            GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}