name: migration-template
on:
    workflow_call:
        inputs:
            migration_type:
                description: "Migrate repo or pipeline - allowed values: repo, pipeline"
                required: true
                type: string
                default: "repo"
            script_file_path:
                description: "Script file path"
                required: true
                type: string
            workflow_migration_audit:
                description: "Whether audit pipeline migration or not"
                required: false
                default: false
                type: boolean
            github_user_name:
                description: "GitHub user name"
                required: true
                type: string
            github_repo_name:
                description: "GitHub repo name"
                required: true
                type: string
            gitlab_user_name:
                description: "GitLab user name"
                required: true
                type: string
            gitlab_repo_name:
                description: "GitLab repo name"
                required: true
                type: string
        secrets:
            GH_TOKEN:
                description: "GitHub personal access token"
                required: true
            GITLAB_TOKEN:
                description: "GitLab personal access token"
                required: true

jobs:
    validate-file-execution-permission:
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repository on the runner
          uses: actions/checkout@v4
          with:
            persist-credentials: false

        - name: Validate if given file is executable
          run: |
            if [ -x ${{ inputs.script_file_path }} ]; then
              echo "File is executable."
            else
              echo "File is not executable."
              ls
              chmod +x ${{ inputs.script_file_path }}
            fi
            tar -cvf executable_file.tar ${{ inputs.script_file_path }}

        - name: Upload executable as artifact
          uses: actions/upload-artifact@v4
          with:
            name: executable-file
            path: ./executable_file.tar
            if-no-files-found: error

    run-repo-migration-script:
        needs: validate-file-execution-permission
        if: ${{ inputs.migration_type == 'repo' }}
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repository on the runner
              uses: actions/checkout@v4
              with:
                persist-credentials: false

            - name: Download executable file
              uses: actions/download-artifact@v4
              with:
                name: executable-file
                path: ./

            - name: Unpack the tar file
              run: tar -xvf executable_file.tar
            
            - name: Run repo migration script
              env:
                GH_TOKEN: ${{ secrets.GH_TOKEN }}
                GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }} 
              run: ${{ inputs.script_file_path }} ${{ inputs.github_user_name }} ${{ inputs.github_repo_name }} ${{ inputs.gitlab_user_name }} ${{ inputs.gitlab_repo_name }}

    run-pipeline-migration-script:
        needs: validate-file-execution-permission
        if: ${{ inputs.migration_type == 'pipeline' }}
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repository on the runner
            uses: actions/checkout@v4
            with:
              persist-credentials: false

          - name: Download executable file
            uses: actions/download-artifact@v4
            with:
              name: executable-file
              path: ./

          - name: Unpack the tar file
            run: tar -xvf executable_file.tar

          - name: Run pipeline migration script
            env:
              GH_TOKEN: ${{ secrets.GH_TOKEN }}
              GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
              CUR_GITHUB_REPO: ${{ github.repository }}
              GITHUB_SHA: ${{ github.sha }}
            run: ${{ inputs.script_file_path }} ${{ inputs.workflow_migration_audit }} ${{ inputs.github_user_name }} ${{ inputs.github_repo_name }} ${{ inputs.gitlab_user_name }} ${{ inputs.gitlab_repo_name }}