name: migration-template
on:
    workflow_call:
        inputs:
            migration_type:
                description: "Migrate repo or pipeline - allowed values: repo, pipeline"
                required: true
                type: string
                default: "repo"
            script_file_path:
                description: "Script file path"
                required: true
                type: string
            workflow_migration_audit:
                description: "Whether audit pipeline migration or not"
                required: false
                default: false
                type: boolean
            github_user_name:
                description: "GitHub user name"
                required: true
                type: string
            github_repo_name:
                description: "GitHub repo name"
                required: true
                type: string
            gitlab_user_name:
                description: "GitLab user name"
                required: true
                type: string
            gitlab_repo_name:
                description: "GitLab repo name"
                required: true
                type: string
        secrets:
            GH_TOKEN:
                description: "GitHub personal access token"
                required: true
            GITLAB_TOKEN:
                description: "GitLab personal access token"
                required: true

jobs:
    run_migration_script:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repository o the runner
              uses: actions/checkout@v4
              with:
                persist-credentials: false

            - name: Check file permission
              run: ls -la ${{ inputs.script_file_path }}
              
            - name: Change file permission
              run: |
                chmod +x ${{ inputs.script_file_path }}
                echo "verify permissions of target files"
                ls -la ${{ inputs.script_file_path }}
            
            - name: Run repo migration script
              if: ${{ inputs.migration_type == 'repo' }}
              env:
                GH_TOKEN: ${{ secrets.GH_TOKEN }}
                GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }} 
              run: ${{ inputs.script_file_path }} ${{ inputs.github_user_name }} ${{ inputs.github_repo_name }} ${{ inputs.gitlab_user_name }} ${{ inputs.gitlab_repo_name }}

            - name: Run pipeline migration script
              if: ${{ inputs.migration_type == 'pipeline' }}
              env:
                GH_TOKEN: ${{ secrets.GH_TOKEN }}
                GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }} 
              run: ${{ inputs.script_file_path }} ${{ inputs.workflow_migration_audit }} ${{ inputs.github_user_name }} ${{ inputs.github_repo_name }} ${{ inputs.gitlab_user_name }} ${{ inputs.gitlab_repo_name }}      