name: migrate-ecs-gitlab
run-name: Migrate GitLab repo
on:
  workflow_dispatch:
    inputs:
      github_repo:
        description: "GitHub repo name"
        required: true
        type: string
      github_user_name:
        description: "GitHub user name"
        required: true
        type: string
      gitlab_repo:
        description: "GitLab repo clone HTTPS"
        required: true
        type: string
      gitlab_user_name:
        description: "GitLab user name"
        required: true
        type: string

jobs:
  validate-config:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository o the runner
        uses: actions/checkout@v4
      
      - name: Check file permission
        run: ls -la ./migrate.sh
      
      - name: Change file permission
        run: |
          chmod +x ./migrate.sh
          echo "verify permissions of target files"
          ls -la ./verify-installation.sh
      
      - name: Run migration script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_MIGRATION_PERSONAL_TOKEN }}
        run: |
          if git ls-remote --heads --exit-code https://${{ github.event.inputs.github_user_name }}:$GH_TOKEN@github.com/${{ github.event.inputs.github_user_name }}/${{ github.event.inputs.github_repo }}.git >/dev/null; then
            echo "Repository exists."
          else
            echo "Repository not found or access denied. $?"
          fi