name: migrate-gitlab-pipeline
run-name: Migrate GitLab pipeline
on:
  workflow_dispatch:
    inputs:
      workflow_migration_audit:
        description: "Whether audit pipeline migration or not"
        required: false
        default: true
        type: boolean
      github_user_name:
        description: "GitHub user name"
        required: false
        type: string
      github_repo_name:
        description: "GitHub repo name"
        required: false
        type: string
      gitlab_user_name:
        description: "GitLab user or group name. Audit mode can only accept group name"
        required: false
        type: string
      gitlab_repo_name:
        description: "GitLab repo name"
        required: false
        type: string

jobs:
  config-github-actions-importer:
    uses: ./.github/workflows/migration_template.yml
    with:
      migration_type: "pipeline"
      script_file_path: "./pipeline-migration.sh"
      workflow_migration_audit: ${{ github.event.inputs.workflow_migration_audit == 'true' }}
      github_user_name: "TminFan"
      github_repo_name: "swen304-project2"
      gitlab_user_name: "my_group"
      gitlab_repo_name: "swen304-project2"
    secrets: 
      GH_TOKEN: ${{ secrets.MIGRATION_PERSONAL_TOKEN }}
      GITLAB_TOKEN: ${{ secrets.GITLAB_MIGRATION_PERSONAL_TOKEN }}