name: migrate-gitlab-repo
run-name: Migrate GitLab repo
on:
  workflow_dispatch:
    inputs:
      github_user_name:
        description: "GitHub user name"
        required: true
        type: string
      github_repo_name:
        description: "GitHub repo name"
        required: true
        type: string
      gitlab_user_name:
        description: "GitLab user name"
        required: true
        type: string
      gitlab_repo_full_path:
        description: "GitLab repo fully qualified domain name. e.g. https://gitlab.com/user-account/project1"
        required: true
        type: string

jobs:
  migrate_repo:
    uses: ./.github/workflows/migration_template.yml
    with:
      migration_type: "repo"
      script_file_path: "./repo-migration.sh"
      is_github_organisation: false
      github_user_name: ${{ github.event.inputs.github_user_name }}
      github_repo_name: ${{ github.event.inputs.github_repo_name }}
      gitlab_user_name: ${{ github.event.inputs.gitlab_user_name }}
      gitlab_repo_name: ${{ github.event.inputs.gitlab_repo_full_path }}
    secrets: 
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}